//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseFirstGaragesProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentLog
    {
        public int Id { get; set; }
        public Nullable<int> Id_Garage { get; set; }
        public Nullable<int> Id_Electricity { get; set; }
        public Nullable<int> Id_Rent { get; set; }
        public Nullable<int> ElectricityAmount { get; set; }
        public Nullable<int> RentAmount { get; set; }
        public Nullable<int> CounterValue { get; set; }
        public string Date { get; set; }
    
        public virtual Electricity Electricity { get; set; }
        public virtual Garage Garage { get; set; }
        public virtual Rent Rent { get; set; }
    }
}
