//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseFirstGarages
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GarageDbEntities : DbContext
    {
        public GarageDbEntities()
            : base("name=GarageDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Electricity> Electricity { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Garage> Garage { get; set; }
        public virtual DbSet<Owner> Owner { get; set; }
        public virtual DbSet<Parking> Parking { get; set; }
        public virtual DbSet<Positions> Positions { get; set; }
        public virtual DbSet<Rent> Rent { get; set; }
        public virtual DbSet<RentLog> RentLog { get; set; }
        public virtual DbSet<SalaryLog> SalaryLog { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
